update action to include references for release and feature branches

diff --git a/.github/python/build-vars/action.yaml b/.github/python/build-vars/action.yaml
--- a/.github/python/build-vars/action.yaml
+++ b/.github/python/build-vars/action.yaml
@@ -41,7 +41,13 @@ runs:
 
       run: |
         PACKAGE="python-dotenv"
+        grep "$PACKAGE" requirements.txt
         SOURCE_VERSION=$(awk -F'==' -v package="$PACKAGE" '$1 == package { print $2; exit; }' requirements.txt | tr -d '\r')
+
+        if [[ -z "$SOURCE_VERSION" ]]; then
+            echo "Error: Could not find $PACKAGE version in requirements.txt."
+            exit 1
+        fi
 
         echo "Extracted version: $SOURCE_VERSION"
 
