update eks image tag

diff --git a/.github/eks/extract-image-tag/action.yaml b/.github/eks/extract-image-tag/action.yaml
--- a/.github/eks/extract-image-tag/action.yaml
+++ b/.github/eks/extract-image-tag/action.yaml
@@ -10,9 +10,6 @@ inputs:
   prod_image:
     description: Tag of the prod image
     required: true
-  image_tag:
-    description: Tag of the built image
-    required: true
 runs:
   using: composite
   steps:
@@ -20,12 +17,22 @@ runs:
         dev_image="${{ inputs.dev_image }}"
         prod_image="${{ inputs.prod_image }}"
 
-        # Extract the tag part from each image
+        # Debug: Print the full image strings to check if they are correctly passed
+        echo "Full DEV_IMAGE: $dev_image"
+        echo "Full PROD_IMAGE: $prod_image"
+
+        # Extract the tag part after the colon (:) from each image
         dev_tag="${dev_image##*:}"
         prod_tag="${prod_image##*:}"
 
         echo "DEV_IMAGE tag: $dev_tag"
         echo "PROD_IMAGE tag: $prod_tag"
+
+        # Ensure the tags are not empty
+        if [ -z "$dev_tag" ] || [ -z "$prod_tag" ]; then
+          echo "Error: One or both image tags could not be extracted."
+          exit 1
+        fi
 
         # Update the Helm values file with the extracted tags
         sed -i "s|dev-image-tag|$dev_tag|g" "${{ inputs.values_file_path }}"
